pub mod claude;
pub mod cli;
pub mod codex;
pub mod discovery;
pub mod error;
pub mod guidance;
pub mod identity;
pub mod model;
pub mod notify;
pub mod opencode;
pub mod os;
mod parser;
pub mod store;
pub mod validate;
