use clap::{Arg, ArgAction, ArgGroup, Command};

// Keep integer overflow for semantic validation, which returns a JSON error.
fn integer_argument(value: &str) -> Result<String, String> {
    let trimmed = value.trim();
    let digits = trimmed.strip_prefix(['+', '-']).unwrap_or(trimmed);
    if !digits.is_empty() && digits.bytes().all(|c| c.is_ascii_digit()) {
        Ok(trimmed.to_owned())
    } else {
        Err(format!("invalid integer value: {value:?}"))
    }
}

pub fn command() -> Command {
    Command::new("htalk")
        .disable_help_subcommand(true)
        .version(env!("CARGO_PKG_VERSION"))
        .disable_version_flag(true)
        .about("htalk: durable local messages with optional client notifications.")
        .after_help("Setup: use one shared database and register both participants.\n  htalk peer discover\n  htalk peer add --help\n\nExchange, using each session's own registered name:\n  htalk --as alice send bob --message 'Please check this.' --wait 45\n  htalk --as bob inbox\n  htalk --as bob ack REQUEST_ID\n  htalk --as bob reply REQUEST_ID --message 'Checked.'\n  htalk --as alice wait REQUEST_ID\n  htalk --as alice ack REPLY_ID\nRead the body before ack. REQUEST_ID and REPLY_ID are message IDs from JSON,\nnot native session IDs. A reply has its own id and an in_reply_to request ID.\n\nPut --db and --as before the command, or set HTALK_DB and HTALK_PEER.\nA command run by a registered Claude Code session can omit --as.\nUse htalk COMMAND --help, or htalk peer COMMAND --help, for examples.\nCommands return JSON with state, submission and recovery guidance.\nExit 0: completed, including send --wait that returned an answer. Exit 2:\ninvalid input, or an unconfirmed notification without an answer; the message\nmay be saved. Exit 130: interrupted; inspect recovery.")
        .arg(Arg::new("version")
            .long("version")
            .help("show program's version number and exit")
            .action(ArgAction::Version)
        )
        .arg(Arg::new("db")
            .long("db")
            .value_name("PATH")
            .help("Shared SQLite file. Default: HTALK_DB, then $XDG_DATA_HOME/harness-talk/mail.sqlite3, then ~/.local/share/harness-talk/mail.sqlite3. Only peer add creates a missing file.")
        )
        .arg(Arg::new("actor")
            .long("as")
            .value_name("NAME")
            .help("Your registered peer name; overrides HTALK_PEER. Without either, message commands use the peer registered for the Claude Code session running them, if recognized.")
        )
        .subcommand_required(true)
        .subcommand(Command::new("mcp")
            .about("Expose this peer's mailbox tools over MCP stdio.")
            .long_about("Run one local MCP stdio server with a fixed database and peer. Set --as or HTALK_PEER. Register the peer before use. Tool calls reuse the ordinary CLI; this server does not wake an idle agent.")
        )
        .subcommand(
            Command::new("peer")
                .disable_help_subcommand(true)
                .about("Discover, register, check and retire session addresses.")
                .long_about("Discover sessions and manage registered addresses. These commands do not message peers.")
                .after_help("Start with htalk peer discover, then htalk peer add --help.\nAfter registering: htalk peer check NAME\nWhen a session is no longer used: htalk peer retire NAME\nUse the same --db PATH before peer for both sessions.")
                .subcommand_required(true)
                .subcommand(
                    Command::new("add")
                        .disable_help_subcommand(true)
                        .about("Register an immutable native or pull peer.")
                .long_about("Save a peer name and native session address, or select --delivery pull for inbox polling without an address. Existing names cannot be reassigned. Does not notify or launch a client.")
                        .after_help("Examples, with the exact session ID and workspace from discovery:\n  htalk peer add alice --harness codex --session SESSION_UUID --workspace /project\n  htalk peer add bob --harness claude --session SESSION_UUID --workspace /project\n  htalk peer add muse --harness opencode --session ses_ID --workspace /project --url http://127.0.0.1:4096\n  htalk peer add helper --harness generic --delivery pull\n\nRegister both peers in the same database. Then run htalk peer check NAME.")
                        .arg(Arg::new("name")
                            .help("Local name: 1–64 lowercase letters, digits, _ or -; start with a letter or digit.")
                            .required(true)
                        )
                        .arg(Arg::new("harness")
                            .long("harness")
                            .help("Harness label. Native: codex, claude or opencode. Pull: any lowercase peer-style ID.")
                            .required(true)
                        )
                        .arg(Arg::new("delivery")
                            .long("delivery")
                            .default_value("native")
                            .value_parser(["native", "pull"])
                            .help("Native client notification, or inbox polling without a native session.")
                        )
                        .arg(Arg::new("session")
                            .long("session")
                            .help("Exact ID from discovery: Codex/Claude UUID or OpenCode ses... ID.")
                            .required_if_eq("delivery", "native")
                        )
                        .arg(Arg::new("workspace")
                            .long("workspace")
                            .help("Session workspace path; must match after resolving paths.")
                            .required_if_eq("delivery", "native")
                        )
                        .arg(Arg::new("socket")
                            .long("socket")
                            .help("Codex only: explicit standalone app-server Unix socket. Omit to use native codex queue.")
                        )
                        .arg(Arg::new("url")
                            .long("url")
                            .help("OpenCode only: loopback server URL (default: http://127.0.0.1:4096).")
                        )
                )
                .subcommand(
                    Command::new("list")
                        .disable_help_subcommand(true)
                        .about("List registered peer addresses.")
                .long_about("Read registered peer names and their immutable session addresses. Retired peers are hidden unless --all is given.")
                        .after_help("Example: htalk --db /shared/mail.sqlite3 peer list\nThese are saved addresses; use peer check NAME to inspect a recipient now.\nretired_hidden counts the retired peers left out.")
                        .arg(Arg::new("all")
                            .long("all")
                            .help("Include retired peers; their retired_at is set.")
                            .action(ArgAction::SetTrue)
                        )
                )
                .subcommand(
                    Command::new("discover")
                        .disable_help_subcommand(true)
                        .about("Find native session addresses.")
                .long_about("Find native session addresses without registering or messaging them. Source statuses describe discovery coverage; an empty result does not prove that no client is running.")
                        .after_help("Examples:\n  htalk peer discover --harness claude --workspace /project\n  htalk peer discover --harness opencode --opencode-url http://127.0.0.1:4096\nUse sessions[].session_id and workspace with peer add; inspect sources for gaps.")
                        .arg(Arg::new("harness")
                            .long("harness")
                            .help("Inspect only this client (default: all three).")
                            .value_parser(["codex", "claude", "opencode"])
                        )
                        .arg(Arg::new("workspace")
                            .long("workspace")
                            .help("Only return sessions matching this resolved workspace path.")
                        )
                        .arg(Arg::new("codex_socket")
                            .long("codex-socket")
                            .help("Inspect this running app-server socket; repeat for several servers.")
                            .action(ArgAction::Append)
                        )
                        .arg(Arg::new("opencode_url")
                            .long("opencode-url")
                            .help("Inspect this local OpenCode server; repeat for several servers.")
                            .action(ArgAction::Append)
                        )
                )
                .subcommand(
                    Command::new("check")
                        .disable_help_subcommand(true)
                        .about("Check a registered session's identity without messaging.")
                .long_about("Verify available identity evidence for a registered peer. Run in the scope that will send; unavailable evidence does not prove that the client is offline.")
                        .after_help("Example: htalk peer check bob\nRun this before send. A successful check does not prove message receipt.")
                        .arg(Arg::new("name")
                            .help("Registered peer name.")
                            .required(true)
                        )
                )
                .subcommand(
                    Command::new("retire")
                        .disable_help_subcommand(true)
                        .about("Refuse new requests to or from a peer that is no longer used.")
                .long_about("Mark a registered peer retired. New requests to or from it are refused, and notices to it are skipped. Replies to saved requests, inbox, show, wait and ack keep working. The name and session stay bound.")
                        .after_help("Example: htalk peer retire bob\npeer list then hides bob; peer list --all shows its retired_at. Repeating keeps\nthe first time. Replies to saved requests remain possible.")
                        .arg(Arg::new("name")
                            .help("Registered peer name.")
                            .required(true)
                        )
                )
                .subcommand(
                    Command::new("restore")
                        .disable_help_subcommand(true)
                        .about("Allow new requests to or from a retired peer again.")
                .long_about("Clear a peer's retirement. Notices skipped while it was retired are not sent. Repeating is safe.")
                        .after_help("Example: htalk peer restore bob")
                        .arg(Arg::new("name")
                            .help("Registered peer name.")
                            .required(true)
                        )
                )
        )
        .subcommand(Command::new("migrate")
            .about("Prepare this mailbox without another operation.")
            .long_about("Ordinary mailbox commands automatically back up and upgrade schema 1/2 on first use. This optional command runs the same preparation on the database selected by --db, HTALK_DB or the default location. Verified backups are kept in PATH.backups. Older binaries reject schema 3. A failed migration rolls back; no automatic downgrade or backup restoration is performed.")
        )
        .subcommand(
            Command::new("send")
                .disable_help_subcommand(true)
                .about("Save a request and attempt one notification.")
                .long_about("Save a request before attempting one notification. After uncertain delivery, recover with show, wait or sent; do not send it again under a new ID.")
                .after_help("Example, after both peers are registered:\n  htalk --as alice send bob --message 'Please check this.' --wait 45\nSave id as REQUEST_ID. If reply is present, read reply.body and ack reply.id.\nOtherwise continue with htalk --as alice wait REQUEST_ID.\nPut --db PATH and --as NAME before send, or use HTALK_DB and HTALK_PEER.")
                .arg(Arg::new("recipient")
                    .help("Registered recipient peer name.")
                    .required(true)
                )
                .arg(Arg::new("id")
                    .long("id")
                    .help("Caller-generated UUID, saved before sending. An identical retry returns the saved request without another notification.")
                )
                .arg(Arg::new("message")
                    .long("message")
                    .help("Nonblank message body, at most 32,000 UTF-8 bytes.")
                )
                .arg(Arg::new("message_file")
                    .long("message-file")
                    .value_name("PATH")
                    .help("Read the same message body from a local text file.")
                )
                .arg(Arg::new("no_notify")
                    .long("no-notify")
                    .help("Save for inbox polling without notifying the client.")
                    .action(ArgAction::SetTrue)
                )
                .arg(Arg::new("wait")
                    .long("wait")
                    .value_name("SECONDS")
                    .help("Wait 0–45 seconds for an answer (default: 0). An answer recorded by this wait before the final notification check skips that notice. It does not resend.")
                    .value_parser(clap::value_parser!(f64)).allow_negative_numbers(true)
                    .default_value("0")
                )
                .group(ArgGroup::new("exclusive_0").args(["message", "message_file"]).required(true))
        )
        .subcommand(
            Command::new("reply")
                .disable_help_subcommand(true)
                .about("Save an answer to an exact request.")
                .long_about("Answer the exact incoming request. An identical retry returns the saved answer without another notification.")
                .after_help("Example: htalk --as bob reply REQUEST_ID --message 'Checked.'\nREQUEST_ID is the incoming question's id from inbox or show.\nThe saved answer has its own id; the original sender acknowledges that answer.")
                .arg(Arg::new("message_id")
                    .help("Incoming request UUID from inbox or show.")
                    .required(true)
                )
                .arg(Arg::new("message")
                    .long("message")
                    .help("Nonblank message body, at most 32,000 UTF-8 bytes.")
                )
                .arg(Arg::new("message_file")
                    .long("message-file")
                    .value_name("PATH")
                    .help("Read the same message body from a local text file.")
                )
                .arg(Arg::new("no_notify")
                    .long("no-notify")
                    .help("Save for inbox polling without notifying the client.")
                    .action(ArgAction::SetTrue)
                )
                .group(ArgGroup::new("exclusive_0").args(["message", "message_file"]).required(true))
        )
        .subcommand(
            Command::new("wait")
                .disable_help_subcommand(true)
                .about("Wait for an answer to a saved request.")
                .long_about("Poll a saved outgoing request for its answer. Record the answer before returning it; a notification that sees this record at its final check is skipped. An already accepted notice may still arrive. Safe to resume after timeout or interruption; does not resend or acknowledge.")
                .after_help("Example: htalk --as alice wait REQUEST_ID --seconds 45\nOn timeout, use this same request ID again. If reply is present, read\nreply.body, then run htalk --as alice ack REPLY_ID using reply.id.")
                .arg(Arg::new("message_id")
                    .help("Outgoing request UUID from send, sent or show.")
                    .required(true)
                )
                .arg(Arg::new("seconds")
                    .long("seconds")
                    .help("Wait 0–45 seconds; 0 checks once (default: 45).")
                    .value_parser(clap::value_parser!(f64)).allow_negative_numbers(true)
                    .default_value("45")
                )
        )
        .subcommand(
            Command::new("show")
                .disable_help_subcommand(true)
                .about("Read a saved message and its correlated answer without acknowledging.")
                .long_about("Read a saved message and its correlated answer without acknowledging.")
                .after_help("Example: htalk --as alice show MESSAGE_ID\nOnly the sender or recipient can show a message. ack_at is its read mark;\nreply is the correlated answer, with its own id and ack_at.")
                .arg(Arg::new("message_id")
                    .help("Message UUID from inbox, sent or another command's result.")
                    .required(true)
                )
        )
        .subcommand(
            Command::new("ack")
                .disable_help_subcommand(true)
                .about("Record that you read an incoming message and remove its pending Codex notice when possible. A question stays open until answered.")
                .long_about("Record that you read an incoming message and remove its pending Codex notice when possible. A question stays open until answered.")
                .after_help("Example: htalk --as alice ack REPLY_ID\nFor an answer returned by wait, use reply.id, not the outgoing request's id.\nRepeated ack is safe. Read notification_cleanup separately: ack may succeed\nwhile cleanup fails. Use recovery.retry_notification_cleanup when returned.\nClaude/OpenCode do not support withdrawing an already queued notice.")
                .arg(Arg::new("message_id")
                    .help("Message UUID from inbox, sent or another command's result.")
                    .required(true)
                )
        )
        .subcommand(
            Command::new("inbox")
                .disable_help_subcommand(true)
                .about("List incoming work that remains open.")
                .long_about("Read incoming unanswered questions and unacknowledged answers, oldest first. Reading changes no acknowledgments.")
                .after_help("Example: htalk --as bob inbox\nRead messages[].body, then ack that message's id. Reply to a question\nusing the same id; acknowledging alone leaves the question open.\nWhen omitted is above 0, run recovery.next_page for newer messages.")
                .arg(Arg::new("limit")
                    .long("limit")
                    .value_name("N")
                    .help("Return at most N messages, 1–500 (default: 20).")
                    .value_parser(integer_argument).allow_negative_numbers(true)
                    .default_value("20")
                )
                .arg(Arg::new("after_seq")
                    .long("after-seq")
                    .value_name("SEQ")
                    .help("Continue with messages newer than this seq; recovery.next_page supplies it.")
                    .value_parser(integer_argument).allow_negative_numbers(true)
                )
        )
        .subcommand(
            Command::new("watch")
                .disable_help_subcommand(true)
                .about("Stream incoming message notices as JSON lines until interrupted.")
                .long_about("Emit ready, then a message event for each open inbox item. Polls locally without model calls. Reading changes no acknowledgments or delivery receipts.")
                .after_help("Example: htalk --as bob watch\nUse for a harness extension that queues notices into its current session.\nEach event contains an id and notification text, not the peer's message body.\nOpen messages appear once per watcher; restarting replays unfinished work.\nAlways show the current message before acting. Run one receiver per peer.")
        )
        .subcommand(
            Command::new("sent")
                .disable_help_subcommand(true)
                .about("List outgoing messages and recover their IDs.")
                .long_about("Recover outgoing IDs after interruption, including messages with uncertain notifications, newest first. Does not resend.")
                .after_help("Example: htalk --as alice sent\nUse a saved request's id with show or wait. Inspect reply for its answer.\nTexts are summarized as body_bytes and body_preview, the first nonblank line\nup to 120 characters; show or --bodies returns them in full.\nWhen omitted is above 0, run recovery.next_page for older messages.\nA saved message with an uncertain notification must not be resent.")
                .arg(Arg::new("limit")
                    .long("limit")
                    .value_name("N")
                    .help("Return at most N messages, 1–500 (default: 20).")
                    .value_parser(integer_argument).allow_negative_numbers(true)
                    .default_value("20")
                )
                .arg(Arg::new("before_seq")
                    .long("before-seq")
                    .value_name("SEQ")
                    .help("Continue with messages older than this seq; recovery.next_page supplies it.")
                    .value_parser(integer_argument).allow_negative_numbers(true)
                )
                .arg(Arg::new("bodies")
                    .long("bodies")
                    .help("Return full message and answer texts.")
                    .action(ArgAction::SetTrue)
                )
        )
}
